name: Build server for linux

on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build server and publish release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v4

    - name: Set up rust
      uses: dtolnay/rust-toolchain@stable

    # Yep, we do run setup-node twice...
    # https://github.com/actions/setup-node/issues/182
    - name: Set up node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Enable corepack
      run: corepack enable

    - name: Set up yarn
      uses: actions/setup-node@v4
      with:
        cache: 'yarn'

    - name: Build
      run: cargo build --release --locked

    - name: Create release
      run: gh release create ${{ github.sha }} target/release/beatdrop
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

